from app.models.base_model import Base
from app.models.nguoidung_model import NguoiDung
from app.models.giasu_model import GiaSu
from app.models.bangcap_model import BangCap
from app.models.khuvuc_model import KhuVuc
from app.models.hocvien_model import HocVien
from app.models.helop_model import HeLop
from app.models.monhoc_model import MonHoc
from app.models.bangcap_monhoc_model import BangCapMonHoc
from app.models.giasu_bangcap_model import GiaSuBangCap
from app.models.giasu_monhoc_model import GiaSuMonHoc
from app.models.giasu_ungtuyen_model import GiaSuUngTuyen
from app.models.khunggio_giasu_monhoc_model import KhungGioGiaSuMonHoc
from app.models.yeucautimgiasu_model import YeuCauTimGiaSu
from app.models.yeucau_hocvien_model import YeuCauHocVien
from app.models.dangkylich_model import DangKyLich
from app.models.chitietdangkylich_model import ChiTietDangKyLich
from app.models.chitietyeucau_model import ChiTietYeuCau
from app.models.danhgia_model import DanhGia
